### ISSUE TITLE
Missing Folders, Files and the selction between own Files, Group Files and the Wolke/Cloud

### ISSUE THREAD

**Issue by Jeisecke** [Lutz-Pfannenschmidt/BetterServ#1]
See on the picture: 
![grafik](https://github.com/user-attachments/assets/5ec60400-0f04-4ddb-bc63-8dc43fd39b98)

Has to look like:
![grafik](https://github.com/user-attachments/assets/7fb6e999-1c69-4ae8-8be6-a26f8d9e704b)

**Comment by Lutz-Pfannenschmidt** [comment]
Thanks for raising this issue, should be resolved now!

**Comment by Jeisecke** [comment]
Thanks, works.
